function HEX(t1,t2,t2r,m_f,mr_f,C,tw,V,kw,b,beta,br,beta_r,rh,rh_r,micro,micro_r,Afr,Afrr,k,row,Af,tic)
epsilon=(t1-t2)/(t1-t2r)
alpha = (b*beta)/(b+br+(2*tw)) % coolant side
alpha_r = (br*beta_r)/(b+br+(2*tw)) % air side'
A = alpha*V % Coolant side
Ar = alpha_r*V
Aw = (A+Ar)/2
omega = alpha*rh
omegar = alpha_r*rh_r
Ac = omega*Afr
Acr = omegar*Afrr
G = m_f*Ac
Gr = mr_f*Acr
Re= rh*G/micro
Rer = rh_r*Gr/micro_r
Re_a = (Re+Rer)/2
Pr =C*micro*row/k %Prandtl number 
Nu_a = 0.023*Re_a^(4/5)*Pr^0.4  % Nusselt number 
St=Nu_a/(Re*Pr)
Str=Nu_a/(Rer*Pr)
St_a=Nu_a/(Re_a*Pr) % Stanton number
h=St*G*C
hr = Str*Gr*C
m = (2*h/kw*tic)
nf = tanh(m*b/2)/(m*b/2)
n0 = 1-((Af/A)*(1- nf))
n0r = 1-((Af/Ar)*(1- nf))
Ntu = m_f*C*((1/n0*h*A)+(1/kw*Aw)+(1/n0r*hr*Ar))
